#include<stdio.h>
int main()
{
    int n,i,j,k=0,x[101],e,f,g=1,h=1,sum=0,p=1,q=1,r=1,rr=1;
    char s[21],c[101];
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%s",s);
        c[i]=s[0];
    }
    c[n]='\0';
    for(i=97;i<=122;i++)
    {
        x[k]=0;
        for(j=0;j<n;j++)
        {
            if(i==(int)c[j])
            {
                x[k]++;
            }
        }
        k++;
    }
    for(i=0;i<26;i++)
    {
        if(x[i]!=0)
        {
            if(x[i]%2==0)
            {
                e=x[i]/2;
                f=e;
                for(i=1;i<=e;i++)
                {
                    g=g*i;
                }
                for(i=1;i<=(e-2);i++)
                {
                    h=h*i;
                }
                sum+=g/h;
            }
            else
            {
                e=x[i]/2;
                f=e+1;
                if(e==1)
                {
                    sum+=0;
                }
                else{
                for(i=1;i<=e;i++)
                {
                    p=p*i;
                }
                for(i=1;i<=(e-2);i++)
                {
                    q=q*i;
                }
                sum+=p/(2*q);
                }
                if(f==1)
                {
                    sum+=0;
                }
                else{
                for(i=1;i<=f;i++)
                {
                    r=r*i;
                }
                for(i=1;i<=(f-2);f++)
                {
                    rr=rr*i;
                }
                sum+=r/(2*rr);
                }
            }
        }
        else
        {
            continue;
        }
    }
    printf("%d",sum);
    return 0;
}
