#include<stdio.h>
int main()
{
    int t,a[5],b[100],c,i,j;
    scanf("%d",&t);
    for(i=0;i<t;i++)
    {
        for(j=0;j<5;j++)
        {
            scanf("%d",&a[j]);
        }
        if((a[0]/2)>=(a[1]+a[2]))
        {
            b[i]=a[1]*a[3]+a[2]*a[4];
        }
        else
        {
            if(a[3]>=a[4])
            {
                if((a[0]/2)>=a[1])
                {
                    c=a[3];
                    b[i]=c*a[1]+((a[0]/2)-a[1])*a[4];
                }
                else
                {
                    b[i]=(a[0]/2)*a[3];
                }

            }
            else
            {
                if((a[0]/2)>=a[2])
                {
                    c=a[4];
                    b[i]=c*a[2]+((a[0]/2)-a[2])*a[3];
                }
                else
                {
                    b[i]=(a[0]/2)*a[4];
                }

            }
        }
    }
    for(i=0;i<t;i++)
    {
        printf("%d\n",b[i]);
    }
}
