#include<stdio.h>
int main()
{
    int x1,y1,x2,y2,x3,y3,x4,y4,i,j,z[30],t;
    scanf("%d",&t);
    for(i=0;i<t;i++)
    {
        scanf("%d%d%d%d%d%d%d%d",&x1,&y1,&x2,&y2,&x3,&y3,&x4,&y4);
        if(x1==x3&&x2==x4&&y1==y3&&y2==y4)
        {
            z[i]=1;
        }
        else
        {
        if(x1<x2)
        {
            if(x3>x1&&x3<x2||x4>x1&&x4<x2)
            {
                if(y1<y2)
                {
                    if(y3>y1&&y3<y2||y4>y1&&y4<y2)
                    {
                        z[i]=1;
                    }
                }
                else
                {
                    if(y3>y2&&y3<y1||y4>y2&&y4<y1)
                    {
                        z[i]=1;
                    }
                }
            }
        }
        else
        {
            if(x3>x2&&x3<x1||x4>x2&&x4<x1)
            {
               if(y1<y2)
                {
                    if(y3>y1&&y3<y2||y4>y1&&y4<y2)
                    {
                        z[i]=1;
                    }
                }
                else
                {
                    if(y3>y2&&y3<y1||y4>y2&&y4<y1)
                    {
                        z[i]=1;
                    }
                }
            }
        }
    }
    }
    for(i=0;i<t;i++)
    {
        printf("Case %d: ",i+1);
        if(z[i]==1)
        {
            printf("YES");
        }
        else
        {
            printf("NO");
        }
        printf("\n");
    }
}
