#include<stdio.h>
int main()
{
    int t,n,a[100000],d[100000],x,y,b,i,j;
    scanf("%d",&t);
    for(i=1;i<=t;i++)
    {
        scanf("%d",&a[i]);
    }
    for(i=1;i<=t;i++)
    {
        b=i+a[i];
        x=0;
        y=0;
        if(b<=(t-i))
        {
        for(j=i+1;j<=b;j++)
        {
            if(a[i]>=a[j])
            {
                if(y>0)
                {
                    continue;
                }
                else
                {
                    x++;
                }
            }
            else
            {
                d[i]=x;
                y=1;
            }
        }
        }
        //
        else
        {
        for(j=i+1;j<=t;j++)
        {
            if(a[i]>=a[j])
            {
                if(y>0)
                {
                    continue;
                }
                else
                {
                    x++;
                }
            }
            else
            {
                d[i]=x;
                y=1;
            }
        }
        }
        //
    }
    for(i=1;i<=t;i++)
    {
        printf("%d\n",d[i]);
    }
}
